config/routes.rb
McMap::Application.routes.draw do
  devise_for :admin_users, path: "admin", path_names: {
    sign_in: "login",
    sign_out: "logout",
  }

  # devise_for :users, :path => "auth",
  #   :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  # devise_scope :admin_user do
  #   get "/admin/login", :to => "devise/sessions#new"
  #   get "/admin/logout", :to => "devise/sessions#destroy"
  # end
  
  root :to => 'map#index'

  namespace :admin do
    root controller: :admin, action: :index
    resources :communities do
      member do
        post "add_coach"
        post "remove_coach"
      end
    end
    resources :members do
    end
  end

  resources :communities do
    collection do
      get "query"
    end
  end

  match "signup", to: "communities#signup_form", via: :get
  match "signup", to: "communities#signup", via: :post

  match "/map" => "map#index"
end

app/models/member.rb
require 'csv'

class Member < ActiveRecord::Base
  attr_accessible :email, :name, :phone_number

  has_and_belongs_to_many :communities, :before_add => :no_duplicates

  before_create :strip_stuff

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      header = []
      header += self.column_names
      header << "Number of communities sign up for"
      csv << header

      self.all.each do |member|
        row = []
        row += member.attributes.values_at(*self.column_names)
        row << member.communities.count

        csv << row
      end
    end
  end

  private

  def strip_stuff
    self.name = self.name.strip
    self.email = self.email.strip
    self.phone_number = self.phone_number.strip
    ["name",
     "email",
     "phone_number",].each do |attr|
       self[attr] = self[attr].try(:strip)
     end
  end

  def no_duplicates(community)
    # ActiveRecord::Rollback is internally captured but not reraised. HABTM
    # doesn't create join if before_add throws exception.
    raise ActiveRecord::Rollback if community.members.include?(self)
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::AdminController
  def index
    @members = Member.all

    respond_to do |format|
      format.html {}
      format.csv { send_data Member.to_csv }
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(params[:member])
    if @member.save
      flash[:notice] = "Successfully created member."
      redirect_to @member
    else
      flash[:notice] = "Failed to create member."
      render :action => 'new'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(params[:member])
      flash[:notice] = "Successfully updated member."
      redirect_to @member
    else
      render :action => 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    flash[:notice] = "Successfully destroyed member."
    redirect_to members_url
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(params[:member])
    if @member.save
      flash[:notice] = "Successfully created member."
      redirect_to @member
    else
      flash[:notice] = "Failed to create member."
      render :action => 'new'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(params[:member])
      flash[:notice] = "Successfully updated member."
      redirect_to @member
    else
      render :action => 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    flash[:notice] = "Successfully destroyed member."
    redirect_to members_url
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/admin/members/index.html.erb
<div id="members">
  <div class="row">
    <div class="span12">
    </div>
  </div>
  <% content_for :data_table_search_left do %>
    <%= link_to "New Member", new_admin_member_path, class: "btn" %>
  <% end %>
  <%= render "admin/shared/data_table_search" %>

  <div class="row">
    <div class="span12">
      <table class="table members">
        <thead>
          <tr>
            <th>Name</th>
            <th>E-mail</th>
            <th>Phone</th>
            <th>Communities</th>
          </tr>
        </thead>
        <% @members.each do |member| %>
          <tr>
            <td><%= link_to(member.name, admin_member_path(member)) %></td>
            <td><%= link_to member.email, "mailto:#{member.email}" %></td>
            <td><%= member.phone_number %></td>
            <td><%= member.communities.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <%= link_to "Export as CSV", admin_members_path(format: :csv) %>
    </div>
  </div>
</div>

app/views/admin/members/new.html.erb
<ul class="breadcrumb">
  <li><a href="<%= admin_members_path %>">Members</a> <span class="divider">/</span></li>
  <li class="active">New Member</li>
</ul>

<%# <%= render 'form', locals: {member: @member} %1> %>

app/views/admin/members/show.html.erb
<div id="member">
  <ul class="breadcrumb">
    <li><a href="<%= admin_members_path %>">Members</a> <span class="divider">/</span></li>
    <li class="active"><%= @member.name %></li>
  </ul>

  <div class="row">
    <table class="attributes-table">
      <tr>
        <td class="attribute-name">Name</td>
        <td><%= @member.name %></td>
      </tr>
      <tr>
        <td class="attribute-name">E-mail</td>
        <td><%= @member.email %></td>
      </tr>
      <tr>
        <td class="attribute-name">Phone</td>
        <td><%= @member.phone_number %></td>
      </tr>
    </table>
    <div><%= link_to "Edit Member", edit_admin_member_path(@member), class: "btn" %></div>
  </div>

  <div class="row">
    <% if @member.communities.blank? %>
    <% else %>
      <h3>Communities</h3>

      <ul>
        <% @member.communities.each do |community| %>
          <li>
          <%= link_to community.title, admin_community_path(community) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>