config/routes.rb
McMap::Application.routes.draw do
  devise_for :admin_users, path: "admin", path_names: {
    sign_in: "login",
    sign_out: "logout",
  }

  # devise_for :users, :path => "auth",
  #   :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  # devise_scope :admin_user do
  #   get "/admin/login", :to => "devise/sessions#new"
  #   get "/admin/logout", :to => "devise/sessions#destroy"
  # end
  
  root :to => 'map#index'

  namespace :admin do
    root controller: :admin, action: :index
    resources :communities do
      member do
        post "add_coach"
        post "remove_coach"
      end
    end
    resources :members do
    end
  end

  resources :communities do
    collection do
      get "query"
    end
  end

  match "signup", to: "communities#signup_form", via: :get
  match "signup", to: "communities#signup", via: :post

  match "/map" => "map#index"
end

app/views/admin/_header.html.erb
<div id="navbar" class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">MC Admin</a>
    <ul class="nav">
      <li data-name="dashboard"><%= link_to "Dashboard", admin_root_path %></li>
      <li data-name="communities"><%= link_to "Communities", admin_communities_path %></li>
      <li data-name="members"><%= link_to "Members", admin_members_path %></li>
    </ul>
    <ul class="nav pull-right">
      <li class="nav-item"><%= current_admin_user.email %></li>
      <li class=""><%= link_to "Logout", destroy_admin_user_session_path, method: :delete %></li>
    </ul>
  </div>
</div>