config/routes.rb
McMap::Application.routes.draw do
  devise_for :admin_users, path: "admin", path_names: {
    sign_in: "login",
    sign_out: "logout",
  }

  # devise_for :users, :path => "auth",
  #   :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  # devise_scope :admin_user do
  #   get "/admin/login", :to => "devise/sessions#new"
  #   get "/admin/logout", :to => "devise/sessions#destroy"
  # end
  
  root :to => 'map#index'

  namespace :admin do
    root controller: :admin, action: :index
    resources :communities do
      member do
        post "add_coach"
        post "remove_coach"
      end
    end
    resources :members do
    end
  end

  resources :communities do
    collection do
      get "query"
    end
  end

  match "signup", to: "communities#signup_form", via: :get
  match "signup", to: "communities#signup", via: :post

  match "/map" => "map#index"
end

app/controllers/admin/communities_controller.rb
class Admin::CommunitiesController < Admin::AdminController
  before_filter :prepare_kind_list, only: [:update, :create]
  before_filter :find_community, only: [:show, :edit, :update]

  def index
    @communities = Community.all

    @members_count = CommunitiesMembers.group(:community_id).where(:community_id => @communities).count
    @taggings_hash = {}
    taggings = ActsAsTaggableOn::Tagging.where(:taggable_id => @communities, :taggable_type => Community, :context => "kinds").includes(:tag)
    taggings.each do |tagging|
      @taggings_hash[tagging.taggable_id] ||= []
      @taggings_hash[tagging.taggable_id] << tagging.tag
    end

    respond_to do |format|
        format.html {}
        format.csv { send_data Community.to_csv }
    end
  end

  def show
  end

  def new
    @community = Community.new
  end

  def edit

    if cannot?(:update, @community)
      flash[:alert] = "Sorry, can't edit because you are not a coach of this community."
      redirect_to admin_community_path(@community)
    end
  end

  def update
    redirect_to :back if cannot?(:update, @community)

    if params[:community]["kind_list"].nil?
      # No kinds were given, so no checkbox values were sent. Add a blank list
      # so Community validations will work.
      params[:community]["kind_list"] = []
    end

    respond_to do |format|
      if @community.update_attributes(params[:community])
        format.html { redirect_to admin_community_path(@community), notice: "Community was successfully updated." }
        format.json { head :no_content }
      else
        flash[:alert] = "Please fix the errors below."
        @error_keys = @community.errors.keys
        format.html { render action: "edit" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    if params[:community]["kind_list"].nil?
      # No kinds were given, so no checkbox values were sent. Add a blank list
      # so Community validations will work.
      params[:community]["kind_list"] = []
    end

    respond_to do |format|
      @community = Community.create(params[:community])

      if @community.valid?
        format.html { redirect_to admin_community_path(@community), notice: "Community was successfully created." }
        format.json { head :no_content }
      else
        flash[:alert] = "Please fix the errors below."
        @error_keys = @community.errors.keys
        format.html { render action: "new" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_coach
    @community = Community.find(params[:id])
    admin_user = AdminUser.find(params[:admin_user_id])
    @community.coaches << admin_user
    redirect_to :back
  end

  def remove_coach
    @community = Community.find(params[:id])
    admin_user = AdminUser.find(params[:admin_user_id])
    @community.coaches.destroy(admin_user)
    redirect_to :back
  end

  private

  def prepare_kind_list
    if params[:community]["kind_list"].nil?
      # No kinds were given, so no checkbox values were sent. Add a blank list
      # so Community validations will work.
      params[:community]["kind_list"] = []
    end
  end

  def find_community
    @community = Community.find(params[:id])
  end
end

app/controllers/admin2/communities_controller.rb
class Admin2::CommunitiesController < Admin2::Admin2Controller
  before_filter :prepare_kind_list, only: [:update, :create]
  before_filter :find_community, only: [:show, :edit, :update]

  def index
    @communities = Community.all

    @members_count = CommunitiesMembers.group(:community_id).where(:community_id => @communities).count
    @taggings_hash = {}
    taggings = ActsAsTaggableOn::Tagging.where(:taggable_id => @communities, :taggable_type => Community, :context => "kinds").includes(:tag)
    taggings.each do |tagging|
      @taggings_hash[tagging.taggable_id] ||= []
      @taggings_hash[tagging.taggable_id] << tagging.tag
    end
  end

  def show
  end

  def new
    @community = Community.new
  end

  def edit
  end

  def update
    if params[:community]["kind_list"].nil?
      # No kinds were given, so no checkbox values were sent. Add a blank list
      # so Community validations will work.
      params[:community]["kind_list"] = []
    end

    respond_to do |format|
      if @community.update_attributes(params[:community])
        format.html { redirect_to admin2_community_path(@community), notice: "Community was successfully updated." }
        format.json { head :no_content }
      else
        flash[:alert] = "Please fix the errors below."
        @error_keys = @community.errors.keys
        format.html { render action: "edit" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    if params[:community]["kind_list"].nil?
      # No kinds were given, so no checkbox values were sent. Add a blank list
      # so Community validations will work.
      params[:community]["kind_list"] = []
    end

    respond_to do |format|
      @community = Community.create(params[:community])

      if @community.valid?
        format.html { redirect_to admin2_community_path(@community), notice: "Community was successfully created." }
        format.json { head :no_content }
      else
        flash[:alert] = "Please fix the errors below."
        @error_keys = @community.errors.keys
        format.html { render action: "new" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_coach
    @community = Community.find(params[:id])
    admin_user = AdminUser.find(params[:admin_user_id])
    @community.coaches << admin_user
    redirect_to :back
  end

  def remove_coach
    @community = Community.find(params[:id])
    admin_user = AdminUser.find(params[:admin_user_id])
    @community.coaches.destroy(admin_user)
    redirect_to :back
  end

  private

  def prepare_kind_list
    if params[:community]["kind_list"].nil?
      # No kinds were given, so no checkbox values were sent. Add a blank list
      # so Community validations will work.
      params[:community]["kind_list"] = []
    end
  end

  def find_community
    @community = Community.find(params[:id])
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  caches_page :index

  def index
    json = Community.visible.all.map(&:output_json)
    respond_to do |format|
      format.json { render :json => json }
    end
  end

  # params:
  #   limit       - Number of results per page, defaults to 50
  #   page        - Page of results to get, defaults to 1 (NOT zero-based)
  #   campus      - Blank, or enum value from Community::CAMPUSES
  #   host_day    - Blank, or enum value from Community::DAYS
  #   kinds       - Blank, or comma-seperated list of enum value from
  #                 Community::MC_KINDS
  #   points_only - True if only minimal point data is to be returned
  #   show_hidden - Show hidden commmunities. Defaults to false.
  def query
    # pull params from the params hash
    limit = (params[:limit] || 50).to_i
    page = (params[:page] || 1).to_i
    points_only = params[:points_only] == 'true'

    # normalize all filter values to lowercase
    filters = params.slice(:campus, :host_day)
    filters.each do |k, v|
      # Turn into array, split by comma, to do IN query.
      # e.g. where host_day IN ('monday', ...)
      filters[k] = v.downcase.split(",")
    end

    unless params[:show_hidden]
      # Don't show hidden
      filters[:hidden] = false
    end

    communities = Community.where(filters).with_kinds(params[:kinds]).page(page).per(limit)
    @response = communities.map do |community|
      response = nil

      # return only minimal point data if specified
      if points_only
        point = {
          type: 'Feature',
          geometry: nil,

          # so the user can look up the full data later
          properties: {
            slug: community.slug,
            campus: community.campus,
          },
        }

        # add the coordinates if they're available
        if (community.lat && community.lng)
          point[:geometry] = {
            type: 'Point',
            coordinates: [community.lng.to_f, community.lat.to_f]
          }
        end

        response = point
      else
        response = community.output_json
      end

    end

    respond_to do |format|
      format.json { render :json => @response }
    end
  end

  def signup_form
    @member = Member.new

    # get the community from the database by its slug
    @community = Community.where(slug: params[:community_id]).first

    # give up if that community doesn't exist
    if @community.blank?
      redirect_to '/404'
      return
    end

    # render the signup form if the community could be found
    respond_to do |format|
      format.html { render 'signup_form' }
    end
  end

  # render the HTML sign up form. this is shown in an iframe on the client.
  def signup
    # ensure we have a member present
    @member = Member.new

    if session.blank?
      # Either did not request with CSRF token or used an invalid CSRF token.
      # In these cases, Rails server resets (blanks out) session.
      respond_to do |format|
        format.html { render 'signup_form' }
      end
      return
    end

    @community = Community.where(slug: params[:community_id]).first

    # give up if no such community exists
    if @community.blank?
      @member.errors.add(:community, 'does not exist')

      respond_to do |format|
        format.html { render 'signup_form' }
      end
      return
    end

    # see whether the member already exists
    email = params[:member].try(:[], :email)
    @member = Member.where(email: email).first

    # create a new member if one didn't exist
    if @member.blank?
      @member = Member.new(params[:member])
      unless @member.save
        respond_to do |format|
          format.html { render 'signup_form' }
        end
        return
      end
    end

    # sign the member up for the given community
    @community.signup!(@member)
    respond_to do |format|
      format.html { render 'signup_success' }
    end
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/admin/communities/_form.html.erb
<%= form_for [:admin, @community], {:html => {:class => "form-horizontal"}} do |f| %>
  <div class="control-group <%= error_classes_for_attributes(:leader_first_name, :leader_last_name) %>">
    <%= f.label :leader_first_name, "Leader", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :leader_first_name, placeholder: "First name" %>
      <%= f.text_field :leader_last_name, placeholder: "Last name" %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:coleader_first_name, :coleader_last_name) %>">
    <%= f.label :coleader_first_name, "Co-leader", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :coleader_first_name, placeholder: "First name" %>
      <%= f.text_field :coleader_last_name, placeholder: "Last name" %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:description) %>">
    <%= f.label :description, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :description, rows: 3, class: "span4" %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:campus) %>">
    <%= f.label :campus, :class => "control-label" %>
    <div class="controls">
      <%= f.select :campus, options_for_select(Community::CAMPUSES.map { |k, v| [v, k] }, @community.campus) %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:host_day) %>">
    <%= f.label :host_day, "Day", :class => "control-label" %>
    <div class="controls">
      <%= f.select :host_day, options_for_select(Community::DAYS.map { |d| [d.titleize, d] }, @community.host_day) %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:kind_list) %>">
    <%= f.label :kind_list, "Kinds", class: "control-label" %>
    <% if @community.errors.include?(:kind_list) %>
      <div class="controls">
        <span class="help-block"><strong><%= @community.errors[:kind_list].first %></strong></span>
      </div>
    <% end %>
    <% Community::MC_KINDS.each do |kind, description| %>
      <div class="controls">
        <label class="checkbox inline" name="kind_list">
          <%= check_box_tag "community[kind_list][]", kind, @community.kind_list.include?(kind.to_s) %>
          <%= description %>
        </label>
      </div>
    <% end %>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:email) %>">
    <%= f.label :email, "E-mail", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:phone_number) %>">
    <%= f.label :phone_number, "Phone Number", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :phone_number %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:address_line_1) %>">
    <%= f.label :address_line_1, "Address", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :address_line_1, :placeholder => "5 Elm St" %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:address_line_2) %>">
    <div class="controls">
      <%= f.text_field :address_line_2 %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:address_city, :address_postal) %>">
    <div class="controls">
      <%= f.text_field :address_city, :placeholder => "City" %>
      <%= f.text_field :address_postal, :placeholder => "Zip", :class => "input-small" %>
    </div>
  </div>
  <div class="control-group <%= error_classes_for_attributes(:hidden) %>">
    <div class="controls">
      <label class="checkbox inline" name="hidden">
        <%= f.check_box :hidden %>
        Hidden from map
      </label>
    </div>
  </div>
  <div class="control-group">
    <div class="form-actions">
      <%= f.submit :class => "btn btn-primary" %>
      <%= f.submit "Cancel", :name => :cancel, :class => "btn" %>
    </div>
  </div>
<% end %>

app/views/admin/communities/edit.html.erb
<ul class="breadcrumb">
  <li><a href="<%= admin_communities_path %>">Communities</a> <span class="divider">/</span></li>
  <li><%= link_to @community.title, admin_community_path(@community)%> <span class="divider">/</span></li>
  <li class="active">Edit</li>
</ul>

<%= render 'form', locals: {community: @community} %>

app/views/admin/communities/index.html.erb
<div id="communities">
  <div class="row">
    <div class="span12">
    </div>
  </div>
  <% content_for :data_table_search_left do %>
    <%= link_to "New Community", new_admin_community_path, class: "btn" %>
  <% end %>
  <%= render "admin/shared/data_table_search" %>

  <div class="row">
    <div class="span12">
      <%= render "admin/shared/communities_table" %>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <%= link_to "Export as CSV", admin_communities_path(format: :csv) %>
    </div>
  </div>
</div>

app/views/admin/communities/new.html.erb
<ul class="breadcrumb">
  <li><a href="<%= admin_communities_path %>">Communities</a> <span class="divider">/</span></li>
  <li class="active">New Community</li>
</ul>

<%= render 'form', locals: {community: @community} %>

app/views/admin/communities/show.html.erb
<div id="community">
  <ul class="breadcrumb">
    <li><a href="<%= admin_communities_path %>">Communities</a> <span class="divider">/</span></li>
    <li class="active"><%= @community.title %></li>
  </ul>

  <ul class="nav nav-tabs">
    <li data-sheet="info"><%= link_to("Info", "#", "data-sheet" => "info") %></li>
    <li data-sheet="coaches"><%= link_to("Coaches", "#", "data-sheet" => "coaches") %></li>
    <li data-sheet="members"><%= link_to("Members", "#", "data-sheet" => "members") %></li>
  </ul>

  <div id="community-info" class="sheet" data-sheet="info" style="display: none;">
    <% if @community.hidden? %>
      <span class="label">Hidden from map</span>
    <% end %>
    <table class="attributes-table">
      <tr>
        <td class="attribute-name">Leader</td>
        <td><%= @community.leader %></td>
      </tr>
      <tr>
        <td class="attribute-name">Co-Leader</td>
        <td><%= @community.coleader %></td>
      </tr>
      <tr>
        <td class="attribute-name">Description</td>
        <td><%= @community.description %></td>
      </tr>
      <tr>
        <td class="attribute-name">Campus</td>
        <td><%= @community.campus_name %></td>
      </tr>
      <tr>
        <td class="attribute-name">Day</td>
        <td><%= @community.host_day.capitalize %></td>
      </tr>
      <tr>
        <td class="attribute-name">Kinds</td>
        <td><%= @community.kinds_display %></td>
      </tr>
      <tr>
        <td class="attribute-name">E-mail</td>
        <td><%= link_to @community.email, "mailto:#{@community.email}" %></td>
      </tr>
      <tr>
        <td class="attribute-name">Phone</td>
        <td><%= @community.phone_number %></td>
      </tr>
      <tr>
        <td class="attribute-name">Address</td>
        <td>
          <address>
            <a href="https://www.google.com/maps?q=<%= @community.address %>" target="_blank">
              <% unless @community.address_line_1.blank? %>
                <%= @community.address_line_1 %><br>
              <% end %>
              <% unless @community.address_line_2.blank? %>
                <%= @community.address_line_2 %><br>
              <% end %>
              <%= "#{@community.address_city}, #{@community.address_province} #{@community.address_postal}" unless @community.address_city.blank? %>
            </a>
          </address>
        </td>
      </tr>
    </table>
    <% if can? :update, @community %>
      <div><%= link_to "Edit Community", edit_admin_community_path(@community), class: "btn" %></div>
    <% end %>
  </div>

  <div id="community-coaches" class="sheet" data-sheet="coaches" style="display: none;">
    <%= render "admin/shared/data_table_search" %>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>E-mail</th>
          <th>Phone</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @community.coaches.each do |coach| %>
          <tr>
            <td><%= coach.name %></td>
            <td><%= link_to coach.email, "mailto:#{coach.email}" %></td>
            <td><%= coach.phone_number %></td>
            <td>Remove</td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% unless @community.coaches.include?(current_admin_user) %>
      <%= form_tag(:controller => 'communities', :action => :add_coach) do %>
        <fieldset>
          <%= hidden_field_tag :admin_user_id, current_admin_user.id %>
          <%= submit_tag "Add me as coach", :class => "btn" %>
        </fieldset>
      <% end %>
    <% else %>
    <% end %>

    <%= form_tag({:controller => 'communities', :action => :add_coach}, {:class => "form-inline"}) do %>
      <fieldset>
        <%= select_tag(:admin_user_id, options_from_collection_for_select(AdminUser.all, :id, :display_name)) %>
        <%= submit_tag "Add coach", :class => "btn" %>
      </fieldset>
    <% end %>
  </div>

  <div id="community-members" class="sheet" data-sheet="members" style="display: none;">
    <%= render "admin/shared/data_table_search" %>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>E-mail</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>
        <% @community.members.each do |member| %>
          <tr>
            <td><%= member.name %></td>
            <td><%= link_to member.email, "mailto:#{member.email}" %></td>
            <td><%= member.phone_number %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>